### ISSUE TITLE
Add POI and Polyline

### ISSUE THREAD

**Issue by heraknos** [NAXAM/mapbox-xamarin-forms#9]
Hello,
I'm trying to add some points of interest and trying to draw a polyline, but I don't see any function for that. There is no documentation. Have you any idea ?

**Comment by kanvuduc** [comment]
@heraknos 

Thank you for trying out our library. It's still in development and we only covers the case we need internally, not all cases covered by Mapbox.

Feel free to fork it, customize it and create a pull request.

Cheers.

**Comment by fleuverouge** [comment]
Hi @heraknos,
You can use [PolylineAnnotation](https://github.com/NAXAM/mapbox-xamarin-forms/blob/master/Naxam.Mapbox.Forms/AnnotationsAndFeatures/PolylineAnnotation.cs) to draw polyline.

Firstly, initialize the annotations list of the mapview (which is recommended to be an observable collection):

`
mapview.Annotations = new ObservableCollection<Annotation>();
`

Then create a polyline with predefined coordinates, or an observable collection of coordinates if you want to update them later:

```
var myPolyline = new PolylineAnnotation()
                    {
                        Id = "my_polyline",
                        Coordinates = new ObservableCollection<Position>(new Position[] { startingPoint })
};
```

If you already has a PolylineFeature, you may use it instead of this newly created annotation.
Finally, add it into the annotations list.

If you want to styling the line, you need to create a new [ShapeSource](https://github.com/NAXAM/mapbox-xamarin-forms/blob/master/Naxam.Mapbox.Forms/ShapeSource.cs) and a [LineLayer](https://github.com/NAXAM/mapbox-xamarin-forms/blob/master/Naxam.Mapbox.Forms/Layers/LineLayer.cs):

```
var source = new ShapeSource("polyline_source", myPolyline);
mapView.MapStyle.CustomSources = new ObservableCollection<ShapeSource>(
    new ShapeSource[] { source }
) ;

var layer = new LineLayer("polyline_layer", "polyline_source")
     {
           LineWidth = 2.0
     };
mapview.MapStyle.CustomLayers = new ObservableCollection<Layer>(new Layer[] { layer });
```

Hope this'll help :)

**Comment by heraknos** [comment]
I will check that, thx.
Any other features for markers ?

**Comment by fleuverouge** [comment]
There are also PointAnnotation, MultiPolylineAnnotation and CircleLayer, which work similar to the example above. You can use `CanShowCalloutChecker` function to set whether callout view should be shown when user taps on a annotation (input is the annotation's Id). For example:

```
            mapview.CanShowCalloutChecker = (annotationId) =>
            {
                if (annotationId != null
                    && annotationId.StartsWith("my_prefix", StringComparison.CurrentCulture))
                {
                    return true;
                }
                return false;
            };
```

There's no function to customize the callout view yet though.
